#!/usr/bin/env bash
set -e

echo Installing hopup...

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
HOP_DIR=${HOP_DIR-"$BASE_DIR/.hop"}
HOP_BIN_DIR="$HOP_DIR/bin"
HOP_MAN_DIR="$HOP_DIR/share/man/man1"

BIN_URL="https://raw.githubusercontent.com/0xtimosarkar/hop/master/hopup/hopup"
BIN_PATH="$HOP_BIN_DIR/hopup"


# Create the .hop bin directory and hopup binary if it doesn't exist.
mkdir -p $HOP_BIN_DIR
curl -# -L $BIN_URL -o $BIN_PATH
chmod +x $BIN_PATH

# Create the man directory for future man files if it doesn't exist.
mkdir -p $HOP_MAN_DIR

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    PREF_SHELL=ash
    ;;
*)
    echo "hopup: could not detect shell, manually add ${HOP_BIN_DIR} to your PATH."
    exit 1
esac

# Only add hopup if it isn't already in PATH.
if [[ ":$PATH:" != *":${HOP_BIN_DIR}:"* ]]; then
    # Add the hopup directory to the path and ensure the old PATH variables remain.
    echo >> $PROFILE && echo "export PATH=\"\$PATH:$HOP_BIN_DIR\"" >> $PROFILE
fi

# Warn MacOS users that they may need to manually install libusb via Homebrew:
if [[ "$OSTYPE" =~ ^darwin ]] && [[ ! -f /usr/local/opt/libusb/lib/libusb-1.0.0.dylib && ! -f /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib ]]; then
    echo && echo "warning: libusb not found. You may need to install it manually on MacOS via Homebrew (brew install libusb)."
fi

echo && echo "Detected your preferred shell is ${PREF_SHELL} and added foundryup to PATH. Run 'source ${PROFILE}' or start a new terminal session to use hopup."
echo "Then, simply run 'hopup' to install the Hop Framework."
